name: CI/CD Deploy direto na VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy files to VM
      uses: appleboy/scp-action@v0.1.4
      with:
        source: "."
        target: "/home/ubuntu/app"
        host: ${{ secrets.VM_IP }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Build and deploy on VM
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.VM_IP }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        timeout: "60m"
        command_timeout: "60m"
        script: |
          cd /home/ubuntu/app
          docker system prune -af
          docker-compose -f compose.yml down
          docker-compose -f compose.yml up -d --build
