name: CI/CD Deploy otimizado

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Build da imagem Docker no GitHub Actions
      run: docker build -t myapp/api:latest .

    - name: Exportar imagem como image.tar.gz
      run: docker save myapp/api:latest | gzip > ./image.tar.gz

    - name: Listar arquivos na pasta atual (debug)
      run: ls -l

    - name: Enviar image.tar.gz para a VM
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.VM_IP }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "./image.tar.gz"
        target: "/home/${{ secrets.VM_USER }}/app"

    - name: Rodar docker-compose na VM com imagem pronta
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.VM_IP }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        timeout: 60m
        command_timeout: 60m
        script: |
          cd /home/${{ secrets.VM_USER }}/app
          docker-compose -f compose.yml down --volumes --remove-orphans
          docker image rm myapp/api:latest || true
          docker load < image.tar.gz
          docker-compose -f compose.yml up -d
