name: CI/CD Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Build project
      run: dotnet build --configuration Release

    - name: Publish project
      run: dotnet publish -c Release -o ./publish

    - name: Copy files to VM via SSH
      uses: appleboy/scp-action@v0.1.4
      with:
        source: "publish/*"
        target: "/home/ubuntu/app"
        host: ${{ secrets.VM_IP }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}

    - name: Run deploy script on VM via SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.VM_IP }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          cd /home/ubuntu/app
          # Exemplo: pare o container, rode docker-compose pull e up
          docker-compose down
          docker-compose up -d --build
